export type StopInfo = { meta: string; description: string };

const rules: Array<[string, StopInfo]> = [
  ["TPE", { meta: "機場 · 國際航班", description: "桃園國際機場是本次旅程的起訖點；請依航空公司建議預留報到、安檢與登機時間。" }],
  ["HKG", { meta: "機場 · 轉機", description: "香港國際機場為國泰航班轉機點；留意下一段航班閘口與登機時間。" }],
  ["MEL", { meta: "機場 · 抵達墨爾本", description: "抵達 Melbourne Airport 後辦理入境與提領行李，再依規劃前往 South Yarra。" }],
  ["SYD", { meta: "機場 · 雪梨航班", description: "Sydney Airport 是雪梨段的抵達或離境點；前往時需預留行李與安檢時間。" }],
  ["Check-in", { meta: "住宿 · 入住", description: "先安頓行李並確認房間與門禁資訊，再依體力安排周邊散步。" }],
  ["Check-out", { meta: "住宿 · 退房", description: "離開前確認行李、護照與房卡，並預留前往機場或下一段交通的時間。" }],
  ["Prahran Market", { meta: "市場 · 南亞拉", description: "Prahran Market 是南亞拉的重要生鮮市場，可逛熟食、蔬果與特色攤位；營業日與時間需出發前確認。" }],
  ["Toorak Road", { meta: "街區 · 散步購物", description: "沿 Toorak Road、Chapel Street 與 Oxford Street 感受 South Yarra 的咖啡、選物與街區生活。" }],
  ["皇家植物園", { meta: "花園 · 河岸散步", description: "墨爾本皇家植物園擁有大片草地、湖景與多樣植物，適合放慢步調並銜接亞拉河夜景。" }],
  ["Royal Botanic Gardens", { meta: "花園 · 城市綠地", description: "皇家植物園以湖景、草地與多樣植物聞名，是市中心附近適合散步休息的綠地。" }],
  ["Lune Russell", { meta: "08:30 · 早餐", description: "以層次分明的可頌聞名；PDF 推薦經典原味、杏仁可頌與 Lemon Curd Cruffin，早上排隊通常較短。" }],
  ["Chinatown", { meta: "上午 · 街區散步", description: "沿 Russell Street 轉入 Little Bourke Street，早晨人潮較少，適合感受墨爾本唐人街較安靜的一面。" }],
  ["州立圖書館", { meta: "10:00 · 文化景點", description: "開館後可直上三樓圓頂閱覽室；對稱書桌與大型穹頂是經典拍攝角度。" }],
  ["Melbourne Central", { meta: "上午 · 建築與購物", description: "可欣賞購物中心內保存的 Coop’s Shot Tower 與大鐘，也可順路稍作休息。" }],
  ["Essensorie", { meta: "下午 · 香氛選物", description: "主打澳洲香氛與身體保養，PDF 建議留意 Roll-On Perfume Oil 與護手霜。" }],
  ["皇家拱廊", { meta: "下午 · 歷史建築", description: "Royal Arcade 與 Block Arcade 以馬賽克地板、鐘樓和古典店舖著稱，可順路選購 Haigh’s 巧克力。" }],
  ["Town Hall", { meta: "黃昏 · 城市地標", description: "墨爾本市政廳與聖保羅大教堂展現城市歷史建築風格，適合短暫參觀與拍照。" }],
  ["Hosier Lane", { meta: "傍晚 · 街頭藝術", description: "墨爾本代表性的塗鴉巷，牆面作品持續更新；傍晚光線能讓色彩與紋理更立體。" }],
  ["Flinders Street", { meta: "傍晚 · 經典地標", description: "黃色立面、圓頂與入口大鐘是最具辨識度的墨爾本畫面，也是市中心重要交通節點。" }],
  ["Degraves Street", { meta: "傍晚 · 巷弄氣氛", description: "狹窄街道聚集咖啡店與戶外座位，入夜亮燈後更有氣氛，適合作為行程尾段的散步路線。" }],
  ["Pidapipó", { meta: "收尾 · 義式冰淇淋", description: "以義式冰淇淋為行程終點，口味選擇多，適合在 Degraves Street 散步後收尾。" }],
  ["Balgownie", { meta: "清晨 · 亞拉河谷", description: "熱氣球行程集合與早餐地點之一，周邊可眺望亞拉河谷的葡萄園與山谷景觀。" }],
  ["熱氣球", { meta: "清晨 · 飛行體驗", description: "清晨升空俯瞰葡萄園與山谷，飛行約一小時；實際起飛需依當天天候與業者確認。" }],
  ["Restaurant 1309", { meta: "早餐 · 酒莊餐廳", description: "位於 Balgownie Estate 的餐飲空間，安排於熱氣球著陸後享用早餐並稍作休息。" }],
  ["Yering Station", { meta: "酒莊 · 品飲", description: "亞拉河谷歷史酒莊之一，行程安排品酒並感受葡萄園與酒莊建築。" }],
  ["Yarra Valley Dairy", { meta: "農場 · 手工起司", description: "以手工乳酪與在地乳製品聞名，適合作為酒莊之間的品嚐停靠點。" }],
  ["Punt Road Wines", { meta: "酒莊 · 品飲", description: "亞拉河谷酒莊停靠點，可接觸當地葡萄酒風格；品飲內容依當日安排為準。" }],
  ["St Huberts", { meta: "酒莊 · 午餐", description: "行程安排在 Cellar Door 享用午餐，並欣賞現代建築與葡萄園景觀。" }],
  ["Domaine Chandon", { meta: "酒莊 · 氣泡酒", description: "以氣泡酒與開闊葡萄園景觀聞名，是亞拉河谷具代表性的酒莊停靠點。" }],
  ["Chocolateries", { meta: "甜點 · 巧克力", description: "Yarra Valley Chocolaterie 可選購巧克力、冰淇淋與伴手禮，作為酒莊行程的甜點站。" }],
  ["野生袋鼠", { meta: "野生動物 · 黃昏", description: "在亞拉河谷周邊尋找野生袋鼠；保持距離、不餵食，並依司機與現場狀況調整。" }],
  ["Geelong", { meta: "海岸城市 · 中途停靠", description: "維多利亞州重要港灣城市，也是前往 Great Ocean Road 的常見中途停靠點。" }],
  ["Memorial Arch", { meta: "大洋路 · 紀念地標", description: "Great Ocean Road Memorial Arch 紀念參與築路的退伍軍人，是大洋路經典入口地標。" }],
  ["Lorne", { meta: "海濱小鎮 · 午餐", description: "Lorne 位於大洋路海岸線上，可在小鎮用餐、散步並欣賞海灣景色。" }],
  ["Cape Patton", { meta: "觀景台 · 海岸風景", description: "Cape Patton Lookout 可俯瞰蜿蜒海岸與南大洋，是大洋路沿途視野開闊的停靠點。" }],
  ["十二門徒", { meta: "自然景觀 · 石灰岩海岸", description: "海浪侵蝕形成的石灰岩柱群，是大洋路最具代表性的景觀；風勢強，注意保暖與步道安全。" }],
  ["Loch Ard Gorge", { meta: "自然景觀 · 海蝕峽谷", description: "以沉船歷史、陡峭崖壁與狹長海灣聞名，可沿步道從不同角度欣賞地貌。" }],
  ["Queen Victoria Market", { meta: "06:00–15:00 · 市場", description: "QVM 是墨爾本大型傳統市場，可尋找熟食、農產與伴手禮；週一、週三休市。" }],
  ["Carlton Gardens", { meta: "世界遺產 · 花園", description: "Carlton Gardens 與皇家展覽館構成重要歷史景觀，適合散步欣賞花園與建築外觀。" }],
  ["Melbourne Museum", { meta: "博物館 · 自然與文化", description: "展覽涵蓋維多利亞自然史、原住民文化與城市發展，可依興趣挑選重點展區。" }],
  ["Lygon Street", { meta: "午餐 · 小義大利", description: "Carlton 的義大利文化街區，聚集披薩、義大利麵、甜點與咖啡店。" }],
  ["墨爾本大學", { meta: "校園 · 建築散步", description: "可沿歷史校舍與綠地漫步，感受墨爾本北側的學術與城市氛圍。" }],
  ["Fitzroy", { meta: "文青街區 · 選物與餐飲", description: "以街頭藝術、獨立店舖與多元餐飲聞名，適合安排午後散步和晚餐。" }],
  ["Spencer Outlet", { meta: "購物 · Outlet", description: "位於 Southern Cross 一帶，可集中選購運動與休閒品牌；留意當日營業時間。" }],
  ["Brighton Bathing Boxes", { meta: "上午 · 彩虹小屋", description: "海灘上的彩色木屋是墨爾本經典拍照地點，PDF 建議利用早上較好的光線前往。" }],
  ["Maru", { meta: "動物園 · 澳洲動物", description: "可近距離觀察無尾熊、袋鼠與袋熊等澳洲動物，互動活動依園方當日安排。" }],
  ["Churchill Island", { meta: "農場 · 傳統體驗", description: "體驗澳洲傳統農場生活，可觀賞農場活動與接觸小動物。" }],
  ["Nobbies", { meta: "海岸步道 · 野生動物", description: "沿木棧道欣賞 Phillip Island 西端海岸與海豹岩，風勢通常較強。" }],
  ["Penguin Parade", { meta: "日落 · 小企鵝歸巢", description: "日落後觀賞小企鵝從海上返回巢穴；現場禁止使用閃光燈並建議攜帶保暖衣物。" }],
  ["NGV", { meta: "美術館 · 藝術展覽", description: "National Gallery of Victoria 收藏澳洲與國際藝術，入館後可依當日展覽選擇重點參觀。" }],
  ["South Melbourne Market", { meta: "市場 · 午餐", description: "以海鮮、熟食、咖啡與特色小店聞名，可安排午餐並採買伴手禮。" }],
  ["DFO South Wharf", { meta: "購物 · Outlet", description: "位於 South Wharf 的暢貨中心，品牌選擇多；建議事先列好採買清單控制停留時間。" }],
  ["Chapel Street", { meta: "街區 · 購物散步", description: "橫跨 South Yarra、Prahran 與 Windsor，聚集時尚、咖啡、餐廳與生活選物。" }],
  ["Southern Cross", { meta: "交通 · 城際車站", description: "墨爾本主要城際交通樞紐，前往 Ballarat 或機場時需確認月台與發車時間。" }],
  ["Ballarat Station", { meta: "交通 · 轉乘", description: "抵達 Ballarat 後依行程轉乘公車前往 Sovereign Hill，回程也需留意班次銜接。" }],
  ["Red Hill Mine", { meta: "Sovereign Hill · 礦坑", description: "透過礦坑與淘金故事了解 Ballarat 金礦時代，部分活動需依現場場次參加。" }],
  ["淘金體驗", { meta: "Sovereign Hill · 互動體驗", description: "在淘金區嘗試以淘金盤尋找金砂，是認識 1850 年代淘金熱的代表活動。" }],
  ["馬車", { meta: "Sovereign Hill · 歷史街景", description: "搭乘或觀看馬車穿行歷史街區，感受仿 19 世紀淘金小鎮的氛圍。" }],
  ["Ballarat Wildlife Park", { meta: "備選 · 野生動物園", description: "若時間與交通允許，可近距離觀察澳洲原生動物；是否前往依當日行程取捨。" }],
  ["Lake Wendouree", { meta: "備選 · 湖畔散步", description: "Ballarat 市區的大型湖泊，適合短暫散步；是否停留需配合回程火車時間。" }],
  ["Darling Harbour", { meta: "傍晚 · 港灣散步", description: "雪梨市中心的濱水休閒區，適合抵達後散步、用餐並欣賞夜景。" }],
  ["QVB", { meta: "歷史建築 · 購物", description: "Queen Victoria Building 以彩繪玻璃、穹頂與古典室內聞名，是雪梨代表性歷史商場。" }],
  ["Circular Quay", { meta: "港灣 · 交通樞紐", description: "可連接渡輪、火車與輕軌，也是步行前往雪梨歌劇院和 The Rocks 的起點。" }],
  ["Sydney Opera House", { meta: "11:00 · 中文導覽", description: "雪梨代表性建築，本次已預約中文導覽；請依票券指示提前抵達集合地點。" }],
  ["Macquarie", { meta: "觀景點 · 明信片視角", description: "Mrs Macquarie’s Chair 可同框拍攝雪梨歌劇院與海港大橋，是經典港灣取景位置。" }],
  ["The Mint", { meta: "歷史建築 · Macquarie Street", description: "雪梨殖民時期重要建築之一，可與附近 Hyde Park 和 St Mary’s Cathedral 串成歷史步道。" }],
  ["Hyde Park", { meta: "城市公園 · 散步", description: "雪梨市中心大型綠地，林蔭步道與 Archibald Fountain 適合短暫休息。" }],
  ["St Mary", { meta: "教堂 · 哥德復興建築", description: "St Mary’s Cathedral 以砂岩立面與哥德復興式建築著稱，內部參觀需保持安靜。" }],
  ["Katoomba", { meta: "藍山 · 交通轉乘", description: "Katoomba 是前往 Scenic World、Echo Point 與 Three Sisters 的主要門戶。" }],
  ["Scenic World", { meta: "藍山 · 纜車套票", description: "可搭乘 Scenic Railway、Skyway 與 Cableway，並串連雨林步道；路線依天候與人潮調整。" }],
  ["Skyway", { meta: "景觀纜車 · 峽谷視野", description: "橫越 Jamison Valley 上方，可從高處觀看瀑布、峽谷與 Three Sisters 周邊景觀。" }],
  ["Railway", { meta: "景觀鐵路 · 陡坡體驗", description: "Scenic Railway 以陡峭坡度著稱，下行後可銜接雨林步道。" }],
  ["雨林步道", { meta: "自然步道 · 雨林", description: "在谷底沿木棧道認識藍山雨林與礦業遺跡，請穿著防滑好走的鞋。" }],
  ["Cableway", { meta: "景觀纜車 · 返回上層", description: "由谷底搭乘纜車返回上層園區，可再次俯瞰 Jamison Valley。" }],
  ["Three Sisters", { meta: "藍山 · 代表景觀", description: "Three Sisters 是藍山最具代表性的砂岩地標，可從 Echo Point 欣賞全景。" }],
  ["Leura", { meta: "山城 · 下午散步", description: "Leura 以花園、咖啡館與小店聞名，適合在返程前安排短暫散步。" }],
  ["Gerringong", { meta: "南海岸 · 海濱小鎮", description: "抵達後可沿小鎮與海岸方向散步，前往 Tasma Drive 周邊拍攝特色路牌與田野景色。" }],
  ["Tasma", { meta: "步行 · 特色路牌", description: "依 PDF 規劃從 Gerringong 步行前往 Tasma Drive 的拍照點，來回需預留時間。" }],
  ["Kiama Blowhole", { meta: "自然景觀 · 噴水洞", description: "海浪灌入岩縫時會形成噴水景觀，效果受潮汐、風向與浪況影響。" }],
  ["Kiama", { meta: "南海岸 · 午餐與散步", description: "海濱小鎮適合午餐、逛特色小店，再步行前往 Blowhole 海岸景點。" }],
  ["雪梨魚市場", { meta: "08:30 · 市場早餐", description: "可搭輕軌前往，PDF 推薦牛肉三明治與戶外海鮮攤位；現場選擇依當日營業為準。" }],
  ["雪梨大學", { meta: "11:00 · 校園建築", description: "可參觀 The Quadrangle 大四方院，砂岩建築與拱廊是校園代表性景觀。" }],
  ["Newtown", { meta: "14:00 · Inner West 街區", description: "鄰近雪梨大學的活力街區，聚集咖啡、餐廳、街頭文化與獨立店舖。" }],
  ["Friday Night Market", { meta: "18:00 · 夜市", description: "Dixon Street 一帶的週五夜市，可安排晚餐與小吃；熱門攤位可能需要排隊。" }],
  ["Kirribilli", { meta: "09:00 · 北雪梨", description: "位於海港大橋北側，可感受住宅街區與港灣景觀，並安排咖啡早餐。" }],
  ["The Rocks", { meta: "週末市集 · 歷史街區", description: "雪梨早期殖民歷史街區，週末市集聚集手作、設計與餐飲攤位。" }],
  ["Black Star Pastry", { meta: "14:00 · 甜點", description: "以西瓜草莓蛋糕聞名，適合作為市區行程的甜點停靠點。" }],
];

export function getStopInfo(stop: string): StopInfo {
  const match = rules.find(([keyword]) => stop.toLowerCase().includes(keyword.toLowerCase()));
  return match?.[1] ?? {
    meta: "行程節點 · 查看提醒",
    description: "此站為當日行程或交通節點，請依預約時間、即時班次與現場狀況彈性調整。",
  };
}
